// <auto-generated />
using System;
using DotnetProjectManagement.ProjectManagement.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotnetProjectManagement.ProjectManagement.MigrationService.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    [Migration("20250912212730_Users")]
    partial class Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasDiscriminator().HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectCreatedActivityMember", b =>
                {
                    b.Property<Guid>("ProjectCreatedActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ProjectCreatedActivityId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectCreatedActivityMembers");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectUpdatedActivityMember", b =>
                {
                    b.Property<Guid>("ProjectUpdatedActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("New")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ProjectUpdatedActivityId", "UserId", "New");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUpdatedActivityMembers");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("TaskCreatedActivityId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TaskCreatedActivityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectTaskUser", b =>
                {
                    b.Property<Guid>("AssignedTasksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssigneesId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignedTasksId", "AssigneesId");

                    b.HasIndex("AssigneesId");

                    b.ToTable("ProjectTaskUser");
                });

            modelBuilder.Entity("TaskUpdatedActivityUser", b =>
                {
                    b.Property<Guid>("NewAssigneesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskUpdatedActivityNewAssigneesId")
                        .HasColumnType("uuid");

                    b.HasKey("NewAssigneesId", "TaskUpdatedActivityNewAssigneesId");

                    b.HasIndex("TaskUpdatedActivityNewAssigneesId");

                    b.ToTable("TaskUpdatedActivityUser");
                });

            modelBuilder.Entity("TaskUpdatedActivityUser1", b =>
                {
                    b.Property<Guid>("OldAssigneesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskUpdatedActivityOldAssigneesId")
                        .HasColumnType("uuid");

                    b.HasKey("OldAssigneesId", "TaskUpdatedActivityOldAssigneesId");

                    b.HasIndex("TaskUpdatedActivityOldAssigneesId");

                    b.ToTable("TaskUpdatedActivityUser1");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.Activity");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasIndex("ProjectId");

                    b.HasDiscriminator().HasValue("ProjectActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.TaskActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.Activity");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasIndex("TaskId");

                    b.HasDiscriminator().HasValue("TaskActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectArchivedActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectActivity");

                    b.HasDiscriminator().HasValue("ProjectArchivedActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectCreatedActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectActivity");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasDiscriminator().HasValue("ProjectCreatedActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectRestoredActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectActivity");

                    b.HasDiscriminator().HasValue("ProjectRestoredActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectUpdatedActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectActivity");

                    b.Property<string>("NewDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OldDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasDiscriminator().HasValue("ProjectUpdatedActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.TaskClosedActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.TaskActivity");

                    b.HasDiscriminator().HasValue("TaskClosedActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.TaskCreatedActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.TaskActivity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("DisplayName")
                                .HasColumnName("TaskCreatedActivity_DisplayName");
                        });

                    b.HasDiscriminator().HasValue("TaskCreatedActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.TaskReopenedActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.TaskActivity");

                    b.HasDiscriminator().HasValue("TaskReopenedActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.TaskUpdatedActivity", b =>
                {
                    b.HasBaseType("DotnetProjectManagement.ProjectManagement.Data.Models.TaskActivity");

                    b.Property<string>("NewDescription")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)");

                    b.Property<string>("NewDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OldDescription")
                        .IsRequired()
                        .HasMaxLength(8191)
                        .HasColumnType("character varying(8191)");

                    b.Property<string>("OldDisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("NewDisplayName")
                                .HasColumnName("TaskUpdatedActivity_NewDisplayName");

                            t.Property("OldDisplayName")
                                .HasColumnName("TaskUpdatedActivity_OldDisplayName");
                        });

                    b.HasDiscriminator().HasValue("TaskUpdatedActivity");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.Activity", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.User", "User")
                        .WithMany("History")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectCreatedActivityMember", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectCreatedActivity", "ProjectCreatedActivity")
                        .WithMany("Members")
                        .HasForeignKey("ProjectCreatedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.User", "User")
                        .WithMany("ProjectCreatedActivityMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCreatedActivity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectMember", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectTask", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectUpdatedActivityMember", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectUpdatedActivity", "ProjectUpdatedActivity")
                        .WithMany("Members")
                        .HasForeignKey("ProjectUpdatedActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.User", "User")
                        .WithMany("ProjectUpdatedActivityMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectUpdatedActivity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.User", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.TaskCreatedActivity", null)
                        .WithMany("Assignees")
                        .HasForeignKey("TaskCreatedActivityId");
                });

            modelBuilder.Entity("ProjectTaskUser", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("AssignedTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskUpdatedActivityUser", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("NewAssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.TaskUpdatedActivity", null)
                        .WithMany()
                        .HasForeignKey("TaskUpdatedActivityNewAssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskUpdatedActivityUser1", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OldAssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.TaskUpdatedActivity", null)
                        .WithMany()
                        .HasForeignKey("TaskUpdatedActivityOldAssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectActivity", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.Project", "Project")
                        .WithMany("History")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.TaskActivity", b =>
                {
                    b.HasOne("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectTask", "Task")
                        .WithMany("Activities")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.Project", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectTask", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.User", b =>
                {
                    b.Navigation("History");

                    b.Navigation("ProjectCreatedActivityMemberships");

                    b.Navigation("ProjectMemberships");

                    b.Navigation("ProjectUpdatedActivityMemberships");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectCreatedActivity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.ProjectUpdatedActivity", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("DotnetProjectManagement.ProjectManagement.Data.Models.TaskCreatedActivity", b =>
                {
                    b.Navigation("Assignees");
                });
#pragma warning restore 612, 618
        }
    }
}
