@startuml
left to right direction

rectangle "Web Browser" {
    agent "Blazor WebAssembly" as BlazorWebAssembly
}

cloud "Cloud Services" {

    agent Gateway

    frame "Project Service" {
        agent "Project API" as ProjectAPI
        database "Database" as ProjectDB
    }

    frame "User Service" {
        agent "User API" as UserAPI
    }

    frame "Document Service" {
        agent "Document API" as DocumentAPI
        database "Blob Storage" as DocumentDB
    }

    agent Keycloak
    agent "Message Broker" as MessageBroker
}

BlazorWebAssembly --> Gateway
BlazorWebAssembly --> Keycloak

Gateway --> ProjectAPI
Gateway --> UserAPI
Gateway --> DocumentAPI

ProjectAPI --> ProjectDB
ProjectAPI --> Keycloak
ProjectAPI <-- MessageBroker

UserAPI --> Keycloak

DocumentAPI --> Keycloak
DocumentAPI --> DocumentDB
DocumentAPI --> MessageBroker

@enduml
