@startuml
left to right direction

rectangle "Web Browser" {
    agent "Blazor WebAssembly" as BlazorWebAssembly
}

cloud "Cloud Services" {

    agent Gateway

    frame "ProjectManagement Service" {
        agent "ProjectManagement App" as ProjectAPI
        database "SQL Server" as ProjectDB
    }

    frame Infrastructure {
        agent Redis
        agent Keycloak
    }
}

BlazorWebAssembly --> Gateway
BlazorWebAssembly --> Keycloak

Gateway --> ProjectAPI

ProjectAPI --> ProjectDB
ProjectAPI <-> Redis
ProjectAPI --> Keycloak

@enduml
