@startuml
left to right direction

class Project {
    + Id: Guid
    + DisplayName: string
    + Members: IDictionary<User, ProjectMemberRole>
    + Archived: bool
    + Milestones: ISet<Milestone>
    + Tasks: ISet<Task>
    + History: ISet<ProjectActivity>
}

enum ProjectMemberRole {
    Guest,
    Worker,
    Manager
}

class Milestone {
    + Id: Guid
    + DisplayName: string
    + StartDate: DateOnly?
    + EndDate: DateOnly?
    + Deleted: bool
    + Project: Project
    + Tasks: ISet<Task>
    + History: ISet<MilestoneActivity>
}

class Task {
    + Id: Guid
    + DisplayName: string
    + Description: string
    + Assignees: ISet<User>
    + Milestone: Milestone?
    + Attachments: ISet<<Document>
    + Open: string
    + Project: Project
    + History: IList<TaskActivity>
}

abstract class Activity {
    + Id: Guid
    + User: User
    + Timestamp: DateTimeOffset
}

abstract class ProjectActivity extends Activity {
    + Project: Project
}

class ProjectCreatedActivity extends ProjectActivity {
    + DisplayName: string
    + Members: IDictionary<User, ProjectMemberRole>
}

class ProjectDisplayNameUpdatedActivity extends ProjectActivity {
    + NewDisplayName: string
    + PreviousDisplayName: string
}

class ProjectMembersUpdatedActivity extends ProjectActivity {
    + NewMembers: IDictionary<User, ProjectMemberRole>
    + PreviousMembers: IDictionary<User, ProjectMemberRole>
}

class ProjectArchivedActivity extends ProjectActivity {
}

class ProjectRestoredActivity extends ProjectActivity {
}

abstract class MilestoneActivity extends Activity {
    + Milestone: Milestone
}

class MilestoneCreatedActivity extends MilestoneActivity {
    + DisplayName: string
    + StartDate: DateOnly?
    + EndDate: DateOnly?
}

class MilestoneDisplayNameUpdatedActivity extends MilestoneActivity {
    + NewDisplayName: string
    + PreviousDisplayName: string
}

class MilestoneDatesUpdatedActivity extends MilestoneActivity {
    + NewStartDate: DateOnly?
    + NewEndDate: DateOnly?
    + PreviousStartDate: DateOnly?
    + PreviousEndDate: DateOnly?
}

class MilestoneDeletedActivity extends MilestoneActivity {
}

abstract class TaskActivity extends Activity {
    + Task: Task
}

class TaskCreatedActivity extends TaskActivity {
    + DisplayName: string
    + Description: string
    + Open: string
    + Assignees: ISet<User>
}

class TaskDisplayNameUpdatedActivity extends TaskActivity {
    + NewDisplayName: string
    + PreviousDisplayName: string
}

class TaskDescriptionUpdatedActivity extends TaskActivity {
    + NewDescription : string
    + PreviousDescription: string
}

class TaskAssigneesUpdatedActivity extends TaskActivity {
    + NewAssignees: ISet<User>
    + PreviousAssignees: ISet<User>
}

class TaskMilestoneUpdatedActivity extends TaskActivity {
    + NewMilestone: Milestone?
    + PreviousMilestone: Milestone?
}

class TaskAttachmentsUpdatedActivity extends TaskActivity {
    + NewAttachments: ISet<Document>
    + PreviousAttachments: ISet<Document>
}

class TaskClosedActivity extends TaskActivity {
}

class TaskReopenedActivity extends TaskActivity {
}

class Document {
    + Id: Guid
    + DisplayName: string
    + CreatedTime: DateTimeOffset
    + CreatedBy: User
    + Task: Task?
    + History: IList<TaskAttachmentsUpdatedActivity>
}

class User {
    + Username: string
    + Projects: IDictionary<Projects, ProjectMemberRole>
    + Tasks: ISet<Task>
    + Documents: ISet<Document>
    + History: IList<Activity>
}

Project "1" *-- "0..*" Milestone
Project "1" *-- "0..*" Task
Project "1" *-- "1..*" ProjectActivity
Project "0..*" o-- "0..*" User
Project o-- ProjectMemberRole

Milestone "0..1" --o "0..*" Task
Milestone "1" *-- "1..*" MilestoneActivity

Task "1" *-- "1..*" TaskActivity
Task "0..*" o-- "0..*" User
Task "0..*" o-- "1" Document

Activity "0..*"  o-- "1" User
ProjectCreatedActivity "0..*" o-- "0..*" User
ProjectMembersUpdatedActivity "0..*" o-- "0..*" User
TaskCreatedActivity "0..*" o-- "0..*" User
TaskAssigneesUpdatedActivity "0..*" o-- "0..*" User
TaskAttachmentsUpdatedActivity "0..*" o-- "0..*" Document

Document "0..*" o-- "1" User

@enduml
