@startuml

package "Frameworks and Drivers" {

    map "ProjectManagement.App" as ProjectManagementApp {
    }

    map "ProjectManagement.Migrations.Job" as ProjectManagementMigrationsJob {
    }

    map "ProjectManagement.Migrations" as ProjectManagementMigrations {
    }

    map WebFrontend {
    }

    map Gateway {
    }

    map ServiceDefaults {
    }

    package "Interface Adapters" {

        map "ProjectManagement.Web" as ProjectManagementWeb {
        }

        map "ProjectManagement.Data" as ProjectManagementData {
        }

        package "Application Business Rules" {

            map "ProjectManagement.UseCases" as ProjectManagementUseCases {
            }

            package "Enterprise Business Rules" {

                map "ProjectManagement.Domain" as ProjectManagementDomain {
                }

            }

        }
    }
}

ProjectManagementApp --> ProjectManagementUseCases
ProjectManagementApp --> ProjectManagementMigrations
ProjectManagementApp --> ProjectManagementWeb
ProjectManagementApp --> ServiceDefaults

ProjectManagementUseCases --> ProjectManagementDomain

ProjectManagementMigrationsJob --> ProjectManagementData
ProjectManagementMigrationsJob --> ProjectManagementMigrations
ProjectManagementMigrationsJob --> ServiceDefaults

ProjectManagementMigrations --> ProjectManagementData

ProjectManagementWeb --> ProjectManagementDomain

ProjectManagementData --> ProjectManagementDomain

WebFrontend --> ProjectManagementWeb

Gateway --> ServiceDefaults

@enduml
