@startuml
left to right direction

package Project {
    usecase "Mange Tasks" as manageTasks
    usecase "Assign Tasks to others" as assignTasksToOthers
    usecase "Assign Tasks to yourself" as assignTasksToYourself
    usecase "Read Tasks" as readTasks
}

:Administrator: as admin
:Manager: as manager
:Worker: as worker
:Guest: as guest

admin --> manageTasks
admin --> assignTasksToOthers
admin --> assignTasksToYourself
admin --> readTasks

manager --> manageTasks
manager --> assignTasksToOthers
manager --> assignTasksToYourself
manager --> readTasks

worker --> readTasks
worker --> assignTasksToYourself

guest --> readTasks

@enduml
