//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetProjectManagement.WebFrontend.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DotnetProjectManagement.WebFrontend.Resources.Resources_de", typeof(Resources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        internal static string ProjectsDescription {
            get {
                return ResourceManager.GetString("ProjectsDescription", resourceCulture);
            }
        }
        
        internal static string ActionEdit {
            get {
                return ResourceManager.GetString("ActionEdit", resourceCulture);
            }
        }
        
        internal static string ActionRestore {
            get {
                return ResourceManager.GetString("ActionRestore", resourceCulture);
            }
        }
        
        internal static string ActionArchive {
            get {
                return ResourceManager.GetString("ActionArchive", resourceCulture);
            }
        }
        
        internal static string ProjectsCreateTooltip {
            get {
                return ResourceManager.GetString("ProjectsCreateTooltip", resourceCulture);
            }
        }
        
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        internal static string ProjectMembersCount {
            get {
                return ResourceManager.GetString("ProjectMembersCount", resourceCulture);
            }
        }
        
        internal static string ProjectArchived {
            get {
                return ResourceManager.GetString("ProjectArchived", resourceCulture);
            }
        }
        
        internal static string StateYes {
            get {
                return ResourceManager.GetString("StateYes", resourceCulture);
            }
        }
        
        internal static string StateNo {
            get {
                return ResourceManager.GetString("StateNo", resourceCulture);
            }
        }
        
        internal static string ProjectSaveTitle {
            get {
                return ResourceManager.GetString("ProjectSaveTitle", resourceCulture);
            }
        }
        
        internal static string ProjectNamePlaceholder {
            get {
                return ResourceManager.GetString("ProjectNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string ProjectMemberRole {
            get {
                return ResourceManager.GetString("ProjectMemberRole", resourceCulture);
            }
        }
        
        internal static string ProjectMemberRoleGuest {
            get {
                return ResourceManager.GetString("ProjectMemberRoleGuest", resourceCulture);
            }
        }
        
        internal static string ProjectMemberRoleManager {
            get {
                return ResourceManager.GetString("ProjectMemberRoleManager", resourceCulture);
            }
        }
        
        internal static string ProjectMemberRoleWorker {
            get {
                return ResourceManager.GetString("ProjectMemberRoleWorker", resourceCulture);
            }
        }
        
        internal static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        internal static string ActionSave {
            get {
                return ResourceManager.GetString("ActionSave", resourceCulture);
            }
        }
        
        internal static string FieldErrorRequired {
            get {
                return ResourceManager.GetString("FieldErrorRequired", resourceCulture);
            }
        }
        
        internal static string DisplayNameErrorStringLength {
            get {
                return ResourceManager.GetString("DisplayNameErrorStringLength", resourceCulture);
            }
        }
        
        internal static string UsersDescription {
            get {
                return ResourceManager.GetString("UsersDescription", resourceCulture);
            }
        }
        
        internal static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        internal static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        internal static string ActionLogout {
            get {
                return ResourceManager.GetString("ActionLogout", resourceCulture);
            }
        }
        
        internal static string ActionLogin {
            get {
                return ResourceManager.GetString("ActionLogin", resourceCulture);
            }
        }
        
        internal static string ErrorUnauthorized {
            get {
                return ResourceManager.GetString("ErrorUnauthorized", resourceCulture);
            }
        }
        
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        internal static string GridPaginationItemsTextFormat {
            get {
                return ResourceManager.GetString("GridPaginationItemsTextFormat", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string AppHello {
            get {
                return ResourceManager.GetString("AppHello", resourceCulture);
            }
        }
        
        internal static string DescriptionErrorStringLength {
            get {
                return ResourceManager.GetString("DescriptionErrorStringLength", resourceCulture);
            }
        }
        
        internal static string TasksDescription {
            get {
                return ResourceManager.GetString("TasksDescription", resourceCulture);
            }
        }
        
        internal static string TaskCreateTooltip {
            get {
                return ResourceManager.GetString("TaskCreateTooltip", resourceCulture);
            }
        }
        
        internal static string ActionClose {
            get {
                return ResourceManager.GetString("ActionClose", resourceCulture);
            }
        }
        
        internal static string ActionReopen {
            get {
                return ResourceManager.GetString("ActionReopen", resourceCulture);
            }
        }
        
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        internal static string TaskOpen {
            get {
                return ResourceManager.GetString("TaskOpen", resourceCulture);
            }
        }
        
        internal static string TaskSaveTitle {
            get {
                return ResourceManager.GetString("TaskSaveTitle", resourceCulture);
            }
        }
        
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        internal static string TaskAssigneesCount {
            get {
                return ResourceManager.GetString("TaskAssigneesCount", resourceCulture);
            }
        }
        
        internal static string TaskNamePlaceholder {
            get {
                return ResourceManager.GetString("TaskNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string TaskDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("TaskDescriptionPlaceholder", resourceCulture);
            }
        }
        
        internal static string TaskAssignees {
            get {
                return ResourceManager.GetString("TaskAssignees", resourceCulture);
            }
        }
        
        internal static string ActionNavigateToTasks {
            get {
                return ResourceManager.GetString("ActionNavigateToTasks", resourceCulture);
            }
        }
    }
}
